language: node_js
node_js:
   - "10"
branches:
    only:
       - master
cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g @angular/cli
install:
  - npm install
script:
  - ng build --prod
notifications:
  slack: vdsg:YeRk6YBgJuTEtaRT1pPp76pb
addons:
    apt:
      update: true
